In [1]:
import numpy
import pathlib
import skimage.io
import skimage.transform
import tensorflow

list_imgs_bitmap_gimp = list([file for file in pathlib.Path("dataset/mask/gimp/bitmap/256/mask").rglob("*")])
list_imgs_bitmap_photoshop = list([file for file in pathlib.Path("dataset/mask/photoshop/bitmap/256/png").rglob("*")])
list_imgs_grayscale_photoshop = list([file for file in pathlib.Path("dataset/mask/photoshop/grayscale/original/jpg").rglob("*")])

### valores imgs

In [2]:
img_grayscale_photoshop = skimage.io.imread(list_imgs_grayscale_photoshop[0].resolve())

numpy.unique(img_grayscale_photoshop), img_grayscale_photoshop.shape

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [3]:
img_grayscale_photoshop = skimage.transform.resize(img_grayscale_photoshop, (256, 256), anti_aliasing=True)
numpy.unique(img_grayscale_photoshop), img_grayscale_photoshop.shape, img_grayscale_photoshop.dtype

(array([0.00000000e+00, 2.68075980e-05, 5.36151961e-05, ...,
        9.99444700e-01, 9.99946385e-01, 1.00000000e+00]),
 (256, 256),
 dtype('float64'))

### load_img skimage

In [4]:
img_bitmap_gimp = skimage.io.imread(list_imgs_bitmap_gimp[0].resolve())
img_bitmap_photoshop = skimage.io.imread(list_imgs_bitmap_photoshop[0].resolve())

numpy.unique(img_bitmap_photoshop), img_bitmap_photoshop.shape, numpy.unique(img_bitmap_gimp), img_bitmap_gimp.shape

(array([  0, 255], dtype=uint8),
 (256, 256),
 array([  0, 255], dtype=uint8),
 (256, 256))

### load_img tf

In [5]:
img_bitmap_gimp_decode = tensorflow.io.decode_image(tensorflow.io.read_file(str(list_imgs_bitmap_gimp[0].resolve())))
numpy.unique(img_bitmap_gimp), img_bitmap_gimp.shape #bug metrics

2022-08-23 14:49:56.135231: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-23 14:49:56.154583: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-23 14:49:56.154726: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-23 14:49:56.155211: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

(array([  0, 255], dtype=uint8), (256, 256))

In [6]:
img_bitmap_gimp_load = tensorflow.keras.utils.img_to_array(tensorflow.keras.utils.load_img(str(list_imgs_bitmap_gimp[0].resolve()),color_mode="grayscale"))
numpy.unique(img_bitmap_gimp), img_bitmap_gimp.shape

(array([  0, 255], dtype=uint8), (256, 256))

In [7]:
img_bitmap_gimp_decode = tensorflow.image.resize(img_bitmap_gimp_decode, (256, 256))
numpy.unique(img_bitmap_gimp), img_bitmap_gimp.shape

(array([  0, 255], dtype=uint8), (256, 256))